### ISSUE TITLE
[JOSS] Testing instructions

### ISSUE THREAD

**Issue by pgrete** [AMReX-Astro/MAESTROeX#111]
I was not able to find detailed instructions on how to run the test suite locally.
I infer that I'd have to install the AMReX suite and modify an ini file.
It'd be great if there's an example on how to run the tests, which may facilitate contributions by new developers who don't have access the main repository (and the associated central test infrastructure).
Moreover, this would ensure that (new) userd correctly setup their environment.

linking issue: openjournals/joss-reviews#1757

**Comment by harpolea** [comment]
The test suite runs regression tests that compare the outputs of several test problems against previously computed benchmarks. As the exact outputs of any simulation will vary to some degree between different computational setups (e.g. due to different compilers / versions / hardware), it would not make sense for us to provide a set of benchmarks for others to download and compare their simulations against, as they will almost certainly not agree. 

Before we merge any PR's, we test them using our local test suite. If there are any conflicts, we work with the submitter to resolve these conflicts. At this point, it's normally only a small number of test cases that fail. The webpages listing the results of the test suite describe the full set up of each test case, so it's possible for a user to run the individual tests on their system by using the setups listed. 

As described in the README, we provide a set of unit tests in the `Exec/UNIT_TESTS` directory for simple problems that have analytic / more repeatable solutions. These can be used by a new user to test that they have MAESTROeX properly set up.

**Comment by zingale** [comment]
I've added a chapter on the regression testing with links to the test suite and inputs:

https://amrex-astro.github.io/MAESTROeX/docs/regtest.html

**Comment by pgrete** [comment]
Thanks for the update.
I'm currently trying to understand how this translates to a developer that currently has no access to this repo and uses a separate fork, see #118

**Comment by harpolea** [comment]
Nightly regression tests are triggered automatically, however all other tests (such as those run on PRs) are triggered manually. When triggered manually, the test suite can then be configured to point at e.g. a branch or fork and we can customise which tests are run.

**Comment by pgrete** [comment]
Got it.
