### ISSUE TITLE
[JOSS] Example installation instructions

### ISSUE THREAD

**Issue by pgrete** [AMReX-Astro/MAESTROeX#112]
When I first tried to follow the example in the README or homepage (https://amrex-astro.github.io/MAESTROeX/) my compilation failed as I used an Intel environment.
A small clarification, e.g., "(assuming a gnu compiler suite environment)" would be helpful (as already described in the detailed docs).

linking issue: openjournals/joss-reviews#1757

**Comment by pgrete** [comment]
In addition, the point 8 (Examine the output. https://amrex-astro.github.io/MAESTROeX/docs/getting_started.html) mentioned plotting and restart file.
The test run I conducted resulted in neither `plt` nor `chk` directories. I only have `serial` directories.
Did I do something wrong or have the default been changed (or something else)?

**Comment by harpolea** [comment]
I've added the requirements to the README (b05960c5).

Point 8 says that the plotfiles will be named `pltnnnnn` and the checkpoint files `chknnnn` **by default**. If you look at the inputs file, for this problem `maestro.plot_base_name` had been set to `serial` (so overriding the default). I've reverted this to `plt`. There are were no checkpoint files output as `maestro.chk_int` was set to -1. I've changed this to 1000 so that you should also get one of these output for the example problem. (b05960c5)

There is a plot of the outputs of the `reacting_bubble` problem in the section following the Getting Started section: https://amrex-astro.github.io/MAESTROeX/docs/getting_started.html#working-with-the-output.

**Comment by ajnonaka** [comment]
clarified usage of gnu (added "COMP=gnu") to README on homepage) in 52e0165e0d93721ef9d7a11ea024ff17120a5662
