### ISSUE TITLE
Regression Test Failure

### ISSUE THREAD

**Issue by ajnonaka** [AMReX-Astro/MAESTROeX#18]
See https://ccse.lbl.gov/pub/RegressionTesting/MAESTROeX/

After merging "tiling" into "development", if you build with DEBUG=TRUE and run, these tests crash.  If you build with DEBUG=FALSE they run to completion, so we may not have noticed this before.

**Comment by harpolea** [comment]
I've tried running the double_bubble test with DEBUG=TRUE, and located the crash to here https://github.com/AMReX-Astro/MAESTROeX/blob/497a1059642933cc97cb603291990984e09b7dce/Source/Src_nd/velpred.F90#L347

This is within a function that is not tiled. It seems like there is an error with `utrans` - when I try printing it, the program crashes at a corner (i=64, j=-1). `utrans` is passed as an argument and is calculated by functions called just before `VelPred`. I'll try exploring them to see if I can work out why it might be crashing. My guess would be that something is not being initialised correctly and because the DEBUG mode compiler is stricter it's throwing an error

**Comment by ajnonaka** [comment]
I'll re-run the entire regression suite now and report back.

**Comment by ajnonaka** [comment]
Regression failed because some other commit to amrex breaks compilation.  Looking into the other issue now.

**Comment by ajnonaka** [comment]
Regression test fixed; wdconvect benchmark is being updated.  The tilling implementation changes the order in which random numbers are generated in the velocity initialization, so we will keep the new result.
