### ISSUE TITLE
init_multilevel for planar geometry

### ISSUE THREAD

**Issue by tobyeh** [AMReX-Astro/MAESTROeX#30]
I've been trying to run a two-level 3D calc with planar geometry but currently tells me that init_multilevel has not been implemented for this yet. Is there a work around for this (e.g. single chunk at finest level)?

**Comment by ajnonaka** [comment]
AMR does not work yet even for the single chunk case in planar geometries.  It's currently an open issue and on our TODO list.  The primary modification we will have to make is to ensure that the tagging is done all the way across the domain, since you have to refine across all cells at a lateral height.  If you need AMR soon, you may want to use the original MAESTRO code.

**Comment by ajnonaka** [comment]
Closing this, as we are now actively working on this (as well as planar AMR for all cases) in #6
